"""Primary detector: predict the ``phase`` of every 1-second window.

This is the "stage 1" model. It consumes the same per-window feature
schema produced by ``pipeline/pcap_to_ml_windows.py`` and predicts one
of three classes:

    normal      no attack now and not within the forecast horizon
    pre_attack  the attack ramp is observable on the wire (next ~10 s)
    attack      the attack is currently in steady-state

Operationally, the value of this model is the ``pre_attack`` class --
it gives the SOC a few seconds of lead time before the flood saturates
the target. The ramp is generated by ``Traffic/attack_scripts_C2.sh``
(quadratic 4/16/36/64/100 % steps over ``RAMP_DURATION`` seconds), so
``pre_attack`` is a real, learnable behavioural phase rather than a
labelling artefact.

Inputs
------
``dataset/processed/windows_1s_all.csv``. All rows are used (no
phase-based filtering). Vantages that see no traffic at all (zero
``packet_count``) are dropped so the trainer doesn't waste capacity
modelling pure-silence rows.

Leakage controls
----------------
Same as the secondary trainer: ``capture_id``, ``scenario_id``, and the
absolute/relative timestamps are dropped. Only behavioural features
go into the model.

Outputs (under ``analysis_and_detection/artifacts/``)
-----------------------------------------------------
* ``phase_model.joblib`` -- HistGradientBoosting model + feature list.
* ``phase_confusion_matrix.png``
* ``phase_feature_importances.png``
* ``phase_report.txt`` / ``phase_metrics.json``
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import joblib
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.ensemble import (
    HistGradientBoostingClassifier,
    RandomForestClassifier,
)
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
)
from sklearn.model_selection import (
    GroupKFold,
    StratifiedKFold,
    cross_val_score,
    train_test_split,
)

# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent

DEFAULT_DATA = PROJECT_ROOT / "dataset" / "processed" / "windows_1s_all.csv"
DEFAULT_OUT = SCRIPT_DIR / "artifacts"

PHASES = ["normal", "pre_attack", "attack"]

DROP_COLUMNS = [
    "capture_id",
    "scenario_id",
    "window_start_time",
    "attack_start_time",
    "relative_time",
    "window_duration",
    "phase",
    "attack_family",
]


# ---------------------------------------------------------------------------
def load_phase_rows(csv_path: Path, drop_silent: bool) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    for col in ("phase", "packet_count"):
        if col not in df.columns:
            raise SystemExit(
                f"{csv_path} is missing column '{col}'. "
                "Make sure it was produced by pipeline/pcap_to_ml_windows.py."
            )
    df = df[df["phase"].isin(PHASES)].reset_index(drop=True)

    # Drop the post_attack rows if any older CSVs are mixed in -- they no
    # longer exist as a class.
    if "post_attack" in df["phase"].unique():
        df = df[df["phase"] != "post_attack"].reset_index(drop=True)

    if drop_silent:
        before = len(df)
        df = df[df["packet_count"] > 0].reset_index(drop=True)
        print(f"   dropped {before - len(df)} silent rows (packet_count == 0)")

    if df.empty:
        raise SystemExit("No usable rows after filtering. Check the input CSV.")
    return df


def build_features(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.Series, pd.Series]:
    y = df["phase"].astype(str)
    capture = df["capture_id"].astype(str) if "capture_id" in df.columns else pd.Series(["_"] * len(df))
    X = df.drop(columns=[c for c in DROP_COLUMNS if c in df.columns])
    X = X.apply(pd.to_numeric, errors="coerce").fillna(0.0)
    return X, y, capture


def make_classifier(name: str, seed: int):
    if name == "gbt":
        return HistGradientBoostingClassifier(
            max_iter=600, learning_rate=0.08, max_leaf_nodes=63,
            l2_regularization=0.0, random_state=seed,
        )
    if name == "rf":
        return RandomForestClassifier(
            n_estimators=500, max_features="sqrt", min_samples_leaf=1,
            n_jobs=-1, class_weight="balanced", random_state=seed,
        )
    raise ValueError(f"unknown model: {name!r}")


def evaluate_cv(X, y, groups, model_name, n_splits, seed):
    out = {}

    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)
    out["row_kfold_acc"] = cross_val_score(
        make_classifier(model_name, seed), X, y, cv=skf,
        scoring="accuracy", n_jobs=1,
    ).tolist()
    out["row_kfold_f1"] = cross_val_score(
        make_classifier(model_name, seed), X, y, cv=skf,
        scoring="f1_macro", n_jobs=1,
    ).tolist()

    # Strict: each capture in exactly one fold.
    n_groups = groups.nunique()
    if n_groups >= n_splits:
        gkf = GroupKFold(n_splits=n_splits)
        out["group_kfold_acc"] = cross_val_score(
            make_classifier(model_name, seed), X, y, cv=gkf, groups=groups,
            scoring="accuracy", n_jobs=1,
        ).tolist()
        out["group_kfold_f1"] = cross_val_score(
            make_classifier(model_name, seed), X, y, cv=gkf, groups=groups,
            scoring="f1_macro", n_jobs=1,
        ).tolist()
    else:
        out["group_kfold_acc"] = []
        out["group_kfold_f1"] = []
    return out


def save_confusion_matrix(cm, classes, acc, path):
    fig, ax = plt.subplots(figsize=(6, 5))
    ConfusionMatrixDisplay(cm, display_labels=classes).plot(
        ax=ax, cmap="Greens", colorbar=False, values_format="d"
    )
    ax.set_title(f"Phase confusion matrix  (acc = {acc:.4f})")
    fig.tight_layout()
    fig.savefig(path, dpi=120)
    plt.close(fig)


def save_feature_importances(importances, path, top_n=20):
    fig, ax = plt.subplots(figsize=(8, 8))
    importances.head(top_n).iloc[::-1].plot.barh(ax=ax, color="#1d6f3a")
    ax.set_title(f"Top-{top_n} feature importances (phase model)")
    ax.set_xlabel("importance")
    fig.tight_layout()
    fig.savefig(path, dpi=120)
    plt.close(fig)


def compute_feature_importances(model, X_train, y_train):
    if hasattr(model, "feature_importances_"):
        return pd.Series(model.feature_importances_, index=X_train.columns).sort_values(ascending=False)
    from sklearn.inspection import permutation_importance
    result = permutation_importance(
        model, X_train, y_train, n_repeats=5, random_state=0,
        n_jobs=-1, scoring="f1_macro",
    )
    return pd.Series(result.importances_mean, index=X_train.columns).sort_values(ascending=False)


# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, default=DEFAULT_DATA)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--model", choices=("gbt", "rf"), default="gbt")
    parser.add_argument("--keep-silent", action="store_true",
                        help="Keep rows with packet_count == 0 (vantages "
                             "that see no traffic). Default: drop them.")
    parser.add_argument("--test-size", type=float, default=0.2)
    parser.add_argument("--cv-splits", type=int, default=5)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)

    print(f"== loading {args.data}")
    df = load_phase_rows(args.data, drop_silent=not args.keep_silent)
    print(f"   rows         : {len(df):,}")
    print("   phase counts :")
    for ph, n in df["phase"].value_counts().items():
        print(f"     {ph:<10} {n:>6}")

    X, y, capture = build_features(df)
    print(f"   features     : {X.shape[1]}")
    print(f"   captures     : {capture.nunique()}")
    print(f"   model        : {args.model}")

    print(f"\n== cross-validation")
    cv = evaluate_cv(X, y, capture, args.model, args.cv_splits, args.seed)
    if cv["row_kfold_acc"]:
        rk_acc = sum(cv["row_kfold_acc"]) / len(cv["row_kfold_acc"])
        rk_f1 = sum(cv["row_kfold_f1"]) / len(cv["row_kfold_f1"])
        print(f"   StratifiedKFold (row-shuffle, lax)   acc={rk_acc:.4f}  f1={rk_f1:.4f}")
    if cv["group_kfold_acc"]:
        gk_acc = sum(cv["group_kfold_acc"]) / len(cv["group_kfold_acc"])
        gk_f1 = sum(cv["group_kfold_f1"]) / len(cv["group_kfold_f1"])
        print(f"   GroupKFold by capture_id (strict)    acc={gk_acc:.4f}  f1={gk_f1:.4f}")
    else:
        gk_acc = gk_f1 = None
        print("   GroupKFold skipped (need >= cv_splits unique captures)")

    print(f"\n== held-out test ({1 - args.test_size:.0%} / {args.test_size:.0%})")
    X_tr, X_te, y_tr, y_te = train_test_split(
        X, y, test_size=args.test_size, stratify=y, random_state=args.seed
    )
    clf = make_classifier(args.model, args.seed)
    clf.fit(X_tr, y_tr)
    y_pred = clf.predict(X_te)

    test_acc = accuracy_score(y_te, y_pred)
    test_f1 = f1_score(y_te, y_pred, average="macro")
    print(f"   test accuracy : {test_acc:.4f}")
    print(f"   test f1_macro : {test_f1:.4f}")
    report = classification_report(y_te, y_pred, digits=4)
    print("\n" + report)

    cm = confusion_matrix(y_te, y_pred, labels=PHASES)

    cm_path = args.out / "phase_confusion_matrix.png"
    save_confusion_matrix(cm, PHASES, test_acc, cm_path)
    print(f"   wrote {cm_path}")

    importances = compute_feature_importances(clf, X_tr, y_tr)
    fi_path = args.out / "phase_feature_importances.png"
    save_feature_importances(importances, fi_path)
    print(f"   wrote {fi_path}")

    model_path = args.out / "phase_model.joblib"
    joblib.dump(
        {
            "model": clf,
            "model_kind": args.model,
            "feature_columns": list(X.columns),
            "classes": list(clf.classes_),
            "drop_columns": DROP_COLUMNS,
            "drops_silent_rows": not args.keep_silent,
        },
        model_path,
    )
    print(f"   wrote {model_path}")

    txt_path = args.out / "phase_report.txt"
    with txt_path.open("w", encoding="utf-8") as f:
        f.write("Phase classifier (primary detector)\n")
        f.write("===================================\n\n")
        f.write(f"data           : {args.data}\n")
        f.write(f"model          : {args.model}\n")
        f.write(f"drop_silent    : {not args.keep_silent}\n")
        f.write(f"rows           : {len(df)}\n\n")
        f.write("Phase counts:\n")
        f.write(df["phase"].value_counts().to_string() + "\n\n")
        f.write("Cross-validation (mean across folds):\n")
        if cv["row_kfold_acc"]:
            f.write(f"  StratifiedKFold (row-shuffle): acc={rk_acc:.4f}  f1={rk_f1:.4f}\n")
        if gk_acc is not None:
            f.write(f"  GroupKFold by capture_id:     acc={gk_acc:.4f}  f1={gk_f1:.4f}\n")
        f.write(f"\nHeld-out test ({1 - args.test_size:.0%} / {args.test_size:.0%}):\n")
        f.write(f"  accuracy : {test_acc:.4f}\n")
        f.write(f"  f1_macro : {test_f1:.4f}\n\n")
        f.write("Classification report:\n")
        f.write(report)
        f.write("\nConfusion matrix (rows=true, cols=pred):\n")
        f.write("           " + "  ".join(f"{c:>10}" for c in PHASES) + "\n")
        for i, ph in enumerate(PHASES):
            f.write(
                f"{ph:>10} "
                + "  ".join(f"{cm[i, j]:>10d}" for j in range(len(PHASES)))
                + "\n"
            )
        f.write("\nTop-15 feature importances:\n")
        f.write(importances.head(15).to_string() + "\n")
    print(f"   wrote {txt_path}")

    metrics = {
        "data": str(args.data),
        "model": args.model,
        "drop_silent_rows": not args.keep_silent,
        "n_rows": int(len(df)),
        "phase_counts": df["phase"].value_counts().to_dict(),
        "feature_columns": list(X.columns),
        "cv": cv,
        "test": {
            "test_size": args.test_size,
            "accuracy": float(test_acc),
            "f1_macro": float(test_f1),
            "confusion_matrix": cm.tolist(),
            "labels": PHASES,
        },
        "feature_importances_top10": importances.head(10).to_dict(),
    }
    metrics_path = args.out / "phase_metrics.json"
    metrics_path.write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    print(f"   wrote {metrics_path}")


if __name__ == "__main__":
    main()
